

services:
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    environment:
      RABBIT_DEFAULT_USER: 'rabbitmq'
      RABBIT_DEFAULT_PASS: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_log: